dbt_workshop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: <your_role_name>
      database: <your_database_name>
      warehouse: <your_warehouse_name>
      schema: <your_schema_name>
      threads: 4
